config/routes.rb
Rails.application.routes.draw do
  root to: 'tweets#index'
  resources :tweets

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  paginates_per 5
  validates :message, length: { maximum: 140 }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all.order('created_at DESC')
    @tweets = Tweet.page(params[:page])
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to tweets_url, notice: "タスク「#{@tweet.message}」を登録しました。"
    else
      render :new
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: "タスク「#{@tweet.message}」を削除しました。"
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to tweets_url, notice: "タスク「#{@tweet.message}」を更新しました。"
    else
      render :edit
    end
  end
end


private
  def tweet_params
    params.require(:tweet).permit(:message)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="app-title nav-bar navbar-expend-md navbar-light">
        <div class="navbar-brand">Twitter</div>
      </div>
      <div class="header">
        <%= render "shared/header" %>
      </div>
        <% if flash.notice.present? %>
          <div class="alert alert-success" role="alert">
            <%= flash.notice %>
            <% end %>
          </div>
        <div class="container">
            <div class="sidebar">
            <%= render "shared/sidebar" %>
            </div>
          <div class="main" ><%= yield %></div>
        </div>

  </body>
</html>

app/views/shared/_header.html.erb
<div class="pic1">
  <%= image_tag 'kindai.jpeg', width: '100%'%>
</div>

app/views/shared/_sidebar.html.erb
<h2>近畿大学</h2>
<a href="#">@kindaiPR</a>

<p>近畿大学のTwitter公式アカウントです。
  気象警報による休講情報や、お得なランチ情報など、大学に関する情報を発信します。
  マグロに関するツイート多め🐟学生のみなさんの相談に乗りますので、くだらないことも気軽に話しかけてください。
  履修に関するご質問は所属学部。入試に関するご相談は、入学センターへお問い合わせ下さい。</p>
<p>大阪府東大阪市</p>
<p><%= link_to '新規ツイート', new_tweet_path, class: 'btn btn-info' %></p>

app/views/tweets/_form.html.erb
<% if @tweet.errors.present? %>
  <div class="alert alert-danger" role="alert"><h3>エラーがあります</h3>
    <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= link_to '一覧', tweets_path, class: 'btn btn-info' %>

<%= form_with model: @tweet, local: true do |f| %>
  <p class="form_group"><%= f.label :message, 'メッセージ'%>
    <%= f.text_area :message, row: 5, class: 'form-control', id: 'tweet_message'%></p>
  <p><%= f.submit '登録', class: 'btn btn-primary' %></p>
<% end %>

app/views/tweets/edit.html.erb
<h1>ツイートを編集</h1>

<%= render partial:  'form', locals: {task: @task} %>

app/views/tweets/index.html.erb
<%= page_entries_info @tweets %>
<div class="mb-3">
  <table class="table table-hover">
    <thead class="thead-default">
      <tr>
        <th><%= Tweet.human_attribute_name(:message) %></th>
        <th><%= Tweet.human_attribute_name(:created_at)%></th>
        <th></th>
      </tr>
    </thead>
        <thbody>
          <% @tweets.each do |tw| %>
          <tr>
            <td><%= link_to tw.message, tw %></td>
            <td><time datetime="<%= tw.created_at %>">
              <%= time_ago_in_words(tw.created_at) %>
            </time>
            </td>
            <td>
            <%= link_to '編集', edit_tweet_url(tw), class: 'btn btn-primary mr-3'%>
            <%= link_to '削除', tw, method: :delete, data: { confirm: "タスク「#{tw.message}」を削除してもよろしいですか？"}, class: 'btn btn-danger'%><% end %></td>
          </tr>
        </thbody>
  </table>
</div>
<%= paginate @tweets %>

app/views/tweets/new.html.erb
<h1>新規ツイート</h1>

<%= render partial:  'form', locals: {task: @task} %>

app/views/tweets/show.html.erb
<%= link_to '一覧', tweets_url, class: 'btn btn-info'%>


<table>
  <tbody>
  <tr>
    <th>ツイート</th>
    <td>@tweet.message</td></tr>
  <tr>
    <th>経過時間</th>
    <td><time datetime="<%= @tweet.created_at %>">
      <%= time_ago_in_words(@tweet.created_at) %>
    </time></td>
  </tr>

  </tbody>
</table>